#############################################################################
# Makefile for building: app.app/Contents/MacOS/app
# Generated by qmake (3.1) (Qt 6.0.3)
# Project:  src/qt/app.pro
# Template: app
# Command: /Users/youri/Qt/6.0.3/clang_64/bin/qmake -o Makefile src/qt/app.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.14 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.14 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -Isrc/qt -I. -I/Users/youri/Qt/6.0.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/youri/Qt/6.0.3/clang_64/lib/QtGui.framework/Headers -I/Users/youri/Qt/6.0.3/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Users/youri/Qt/6.0.3/clang_64/mkspecs/macx-clang -F/Users/youri/Qt/6.0.3/clang_64/lib
QMAKE         = /Users/youri/Qt/6.0.3/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/youri/Qt/6.0.3/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/youri/Qt/6.0.3/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = app1.0.0
DISTDIR = /Users/youri/Desktop/LICENCE/S4/LIFAP4-C++/L2-LIFAP4-PROJET/.tmp/app1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.14 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/youri/Qt/6.0.3/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/youri/Qt/6.0.3/clang_64/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework AGL -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/qt/app.cpp \
		src/core/Avis.cpp \
		src/core/EnsembleProfils.cpp \
		src/core/Profil.cpp \
		src/qt/main.cpp moc_app.cpp
OBJECTS       = app.o \
		Avis.o \
		EnsembleProfils.o \
		Profil.o \
		main.o \
		moc_app.o
DIST          = /Users/youri/Qt/6.0.3/clang_64/mkspecs/features/spec_pre.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/device_config.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/unix.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/mac.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/macx.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/sanitize.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/gcc-base.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/clang.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/clang-mac.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/qconfig.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_ext_freetype.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_ext_libpng.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_core_qobject_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_linguist.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_linguist_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_tools_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/qt_functions.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/qt_config.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/spec_post.prf \
		src/qt/.qmake.stash \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/toolchain.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/default_pre.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/resolve_config.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/default_post.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/qml_debug.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/mac.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/warn_on.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/qt.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/resources_functions.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/resources.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/moc.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/uic.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/unix/thread.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/qmake_use.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/file_copies.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/rez.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/exceptions.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/yacc.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/lex.prf \
		src/qt/src/qt/app.pro src/qt/app.h \
		src/core/Avis.h \
		src/core/EnsembleProfils.h \
		src/core/Profil.h src/qt/app.cpp \
		src/core/Avis.cpp \
		src/core/EnsembleProfils.cpp \
		src/core/Profil.cpp \
		src/qt/main.cpp
QMAKE_TARGET  = app
DESTDIR       = 
TARGET        = app.app/Contents/MacOS/app

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 11.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/youri/Desktop/LICENCE/S4/LIFAP4-C++/L2-LIFAP4-PROJET/.qmake.stash
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/youri/Desktop/LICENCE/S4/LIFAP4-C++/L2-LIFAP4-PROJET/src/qt/app.pro


include /Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

app.app/Contents/MacOS/app: ui_app.h $(OBJECTS)  
	@test -d app.app/Contents/MacOS/ || mkdir -p app.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: src/qt/app.pro /Users/youri/Qt/6.0.3/clang_64/mkspecs/macx-clang/qmake.conf /Users/youri/Qt/6.0.3/clang_64/mkspecs/features/spec_pre.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/device_config.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/unix.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/mac.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/macx.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/sanitize.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/gcc-base.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/clang.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/clang-mac.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/qconfig.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_ext_freetype.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_ext_libpng.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_core_qobject_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_linguist.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_linguist_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_tools_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/qt_functions.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/qt_config.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/toolchain.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/default_pre.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/resolve_config.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/default_post.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/qml_debug.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/mac.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/warn_on.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/qt.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/resources_functions.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/resources.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/moc.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/uic.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/unix/thread.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/qmake_use.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/file_copies.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/rez.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/exceptions.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/yacc.prf \
		/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/lex.prf \
		src/qt/app.pro \
		/Users/youri/Qt/6.0.3/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/Users/youri/Qt/6.0.3/clang_64/lib/QtGui.framework/Resources/QtGui.prl \
		/Users/youri/Qt/6.0.3/clang_64/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile src/qt/app.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/spec_pre.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/device_config.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/unix.conf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/mac.conf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/macx.conf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/sanitize.conf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/gcc-base.conf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/clang.conf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/common/clang-mac.conf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/qconfig.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_ext_freetype.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_ext_libpng.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_core_qobject_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_linguist.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_linguist_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_openglwidgets.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_svgwidgets.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_tools_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/qt_functions.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/qt_config.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/sdk.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/toolchain.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/toolchain.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/default_pre.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/resolve_config.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/default_post.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/default_post.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/qml_debug.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/mac.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/warn_on.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/qt.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/resources_functions.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/resources.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/moc.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/unix/opengl.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/uic.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/unix/thread.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/qmake_use.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/file_copies.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/rez.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/testcase_targets.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/exceptions.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/yacc.prf:
/Users/youri/Qt/6.0.3/clang_64/mkspecs/features/lex.prf:
src/qt/app.pro:
/Users/youri/Qt/6.0.3/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/Users/youri/Qt/6.0.3/clang_64/lib/QtGui.framework/Resources/QtGui.prl:
/Users/youri/Qt/6.0.3/clang_64/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile src/qt/app.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

app.app/Contents/PkgInfo: 
	@test -d app.app/Contents || mkdir -p app.app/Contents
	@$(DEL_FILE) app.app/Contents/PkgInfo
	@echo "APPL????" > app.app/Contents/PkgInfo
app.app/Contents/Resources/empty.lproj: 
	@test -d app.app/Contents/Resources || mkdir -p app.app/Contents/Resources
	@touch app.app/Contents/Resources/empty.lproj
	
app.app/Contents/Info.plist: 
	@test -d app.app/Contents || mkdir -p app.app/Contents
	@$(DEL_FILE) app.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.youri.app,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.youri.app,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.14,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,app,g" -e "s,@LIBRARY@,app,g" -e "s,\$${EXECUTABLE_NAME},app,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /Users/youri/Qt/6.0.3/clang_64/mkspecs/macx-clang/Info.plist.app >app.app/Contents/Info.plist

all: Makefile \
		app.app/Contents/PkgInfo \
		app.app/Contents/Resources/empty.lproj \
		app.app/Contents/Info.plist app.app/Contents/MacOS/app

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /Users/youri/Qt/6.0.3/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/qt/app.h src/core/Avis.h src/core/EnsembleProfils.h src/core/Profil.h $(DISTDIR)/
	$(COPY_FILE) --parents src/qt/app.cpp src/core/Avis.cpp src/core/EnsembleProfils.cpp src/core/Profil.cpp src/qt/main.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/qt/app.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r app.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Users/youri/Qt/6.0.3/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.14 -Wall -Wextra -dM -E -o moc_predefs.h /Users/youri/Qt/6.0.3/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_app.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_app.cpp
moc_app.cpp: src/qt/app.h \
		/Users/youri/Qt/6.0.3/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/youri/Qt/6.0.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		src/core/EnsembleProfils.h \
		src/core/Profil.h \
		src/core/Avis.h \
		moc_predefs.h \
		/Users/youri/Qt/6.0.3/clang_64/bin/moc
	/Users/youri/Qt/6.0.3/clang_64/bin/moc $(DEFINES) --include /Users/youri/Desktop/LICENCE/S4/LIFAP4-C++/L2-LIFAP4-PROJET/moc_predefs.h -I/Users/youri/Qt/6.0.3/clang_64/mkspecs/macx-clang -I/Users/youri/Desktop/LICENCE/S4/LIFAP4-C++/L2-LIFAP4-PROJET/src/qt -I/Users/youri/Qt/6.0.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/youri/Qt/6.0.3/clang_64/lib/QtGui.framework/Headers -I/Users/youri/Qt/6.0.3/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.5/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/youri/Qt/6.0.3/clang_64/lib src/qt/app.h -o moc_app.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_app.h
compiler_uic_clean:
	-$(DEL_FILE) ui_app.h
ui_app.h: src/qt/app.ui \
		/Users/youri/Qt/6.0.3/clang_64/bin/uic
	/Users/youri/Qt/6.0.3/clang_64/bin/uic src/qt/app.ui -o ui_app.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

app.o: src/qt/app.cpp src/qt/app.h \
		/Users/youri/Qt/6.0.3/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/youri/Qt/6.0.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		src/core/EnsembleProfils.h \
		src/core/Profil.h \
		src/core/Avis.h \
		ui_app.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o app.o src/qt/app.cpp

Avis.o: src/core/Avis.cpp src/core/Avis.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Avis.o src/core/Avis.cpp

EnsembleProfils.o: src/core/EnsembleProfils.cpp src/core/EnsembleProfils.h \
		src/core/Profil.h \
		src/core/Avis.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnsembleProfils.o src/core/EnsembleProfils.cpp

Profil.o: src/core/Profil.cpp src/core/Profil.h \
		src/core/Avis.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Profil.o src/core/Profil.cpp

main.o: src/qt/main.cpp src/qt/app.h \
		/Users/youri/Qt/6.0.3/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/youri/Qt/6.0.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		src/core/EnsembleProfils.h \
		src/core/Profil.h \
		src/core/Avis.h \
		/Users/youri/Qt/6.0.3/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Users/youri/Qt/6.0.3/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/qt/main.cpp

moc_app.o: moc_app.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_app.o moc_app.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/app/bin || mkdir -p $(INSTALL_ROOT)/opt/app/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/app/bin/app.app
	
	$(QINSTALL) app.app $(INSTALL_ROOT)/opt/app/bin/app.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/app/bin/app.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/app/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

